language: node_js
node_js: stable
# assign build branches
branches:
  only:
    - blog-source

# cache this directory
cache:
  directories:
    - node_modules

env:
  global:
    - GH_REF: github.com/ScarlettCanaan/kohaku.moe.git

# S: Build Lifecycle
before_install:
  - openssl aes-256-cbc -K $encrypted_e9902d4ef12b_key -iv $encrypted_e9902d4ef12b_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - npm install -g hexo-cli # 安装 hexo

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo generate

after_success:
  - git config --global user.name "kohaku"
  - git config --global user.email "drynessgarden495@gmail.com"
  - cd ./public
  - git init
  - git add .
  - git commit -m "update docs"
  #- sed -i'' "/^ *repo/s~github\.com~${githubToken}@github.com~" _config.yml
  - git push --force "https://${github_hexo_token}@${GH_REF}" master:master
  #- hexo deploy
# E: Build LifeCycle
